"""
The blaze-angle pipeline in analyzer.py.

Until now this path was verified only by diffing CSV output against stored
baselines (docs/BASELINES.md). A diff proves the numbers moved; it cannot say
which step moved them. These tests pin the arithmetic instead: the variance
decomposition, the ICC correction, the period bookkeeping, and the shape of the
result dict, each checked against values computed by hand.

The end-to-end tests use a synthetic sawtooth of known blaze angle rather than a
real scan. A real scan has no ground truth to compare against - it can only be
compared to its own previous output, which is what the baselines already do.

Run directly:
    .venv/bin/python tests/test_analyzer.py
"""
import contextlib
import io
import os
import sys
import tempfile
import warnings

import numpy as np

# src/ is placed on the path by tests/conftest.py; repeated here so the file
# also runs directly as a script, not only under pytest.
sys.path.insert(0, os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'src'))

import matplotlib
matplotlib.use('Agg')

from afm_analysis.analyzer import (                                     # noqa: E402
    _analyze_single_file_traditional, _calculate_local_periods,
    _calculate_local_periods_for_grooves, _calculate_periods,
    _calculate_statistics, _calculate_statistics_row_groups,
    _load_and_validate, _package_results, _package_results_row_groups,
    analyze_single_file, analyze_single_file_with_row_groups)
from afm_analysis.settings import AnalysisSettings                      # noqa: E402

# Geometry of the synthetic grating. The scan is an exact whole number of
# periods (2000 nm / 250 nm = 8) so that the linear detrend has as little
# partial-period asymmetry to bite on as possible.
PERIOD_NM = 250.0
SCAN_UM = 2.0
BLAZE_ANGLE_DEG = 30.0
BLAZE_FRAC = 0.75
N_ROW_GROUPS = 5

_cache = {}


# ── Synthetic data ───────────────────────────────────────────────────────────

def _sawtooth_rows(n_rows, n_cols, angle_deg=BLAZE_ANGLE_DEG,
                   period_nm=PERIOD_NM, blaze_frac=BLAZE_FRAC):
    """
    A blazed grating with a blaze angle known by construction.

    Each period is an asymmetric triangle: a long shallow ramp of `blaze_frac`
    of the period rising at `angle_deg`, then a short steep ramp falling back.
    Picking the depth as tan(angle) * blaze_frac * period is what makes the
    long facet sit at exactly the requested angle.

    Rows are identical. Row-to-row structure is what image flattening exists to
    remove and test_image_flatten.py already covers it; leaving it out here
    keeps these tests measuring the angle arithmetic and nothing else.
    """
    x_nm = (SCAN_UM * 1000.0) * np.arange(n_cols) / (n_cols - 1)
    depth_nm = np.tan(np.radians(angle_deg)) * blaze_frac * period_nm

    p = np.mod(x_nm, period_nm)
    rising = p <= blaze_frac * period_nm
    y_nm = np.where(rising,
                    depth_nm * p / (blaze_frac * period_nm),
                    depth_nm * (period_nm - p) / ((1 - blaze_frac) * period_nm))

    return np.tile(y_nm * 1e-9, (n_rows, 1))   # the loaders expect metres


def _write_scan(data, path):
    """
    Write a 2-D array in the text layout core.processing._load_text expects:
    exactly four header lines, then a whitespace-delimited matrix.

    The header deliberately avoids the words the loader sniffs for ("width",
    "scan size"), so the scan size comes from settings.scan_x_size rather than
    from a regex match on prose - one less thing for a test to depend on.
    """
    with open(path, 'w') as f:
        f.write("# Synthetic blazed grating\n"
                "# generated by tests/test_analyzer.py\n"
                "# Value units: m\n"
                "# ---\n")
        for row in data:
            f.write(' '.join(f'{v:.9e}' for v in row) + '\n')


def _scratch():
    """A temporary directory that lives as long as the test session"""
    if 'dir' not in _cache:
        _cache['dir'] = tempfile.TemporaryDirectory()
    return _cache['dir'].name


def _grating_path():
    """The synthetic grating, written once and reused"""
    if 'grating' not in _cache:
        path = os.path.join(_scratch(), 'grating.txt')
        _write_scan(_sawtooth_rows(25, 801), path)
        _cache['grating'] = path
    return _cache['grating']


def _flat_path():
    """A featureless scan: no grooves to find"""
    if 'flat' not in _cache:
        path = os.path.join(_scratch(), 'flat.txt')
        _write_scan(np.zeros((25, 801)), path)
        _cache['flat'] = path
    return _cache['flat']


def _settings(**overrides):
    """
    Settings matched to the synthetic grating.

    blaze_side is 'positive_slope' because the long facet above rises; the
    project default expects it to fall. flatten_method is 'linear' because a
    scan that is flat on average needs nothing cleverer, and level_grooves
    would bring find_peaks tuning into a test that is not about flattening.
    """
    return AnalysisSettings.from_config().with_(
        scan_x_size=SCAN_UM,
        period_est=PERIOD_NM,
        blaze_side='positive_slope',
        flatten_method='linear',
        n_row_groups=N_ROW_GROUPS,
        **overrides)


def _quiet(fn, *args, **kwargs):
    """Run something in analyzer.py without its progress output"""
    with contextlib.redirect_stdout(io.StringIO()):
        return fn(*args, **kwargs)


# ── Groove period bookkeeping ────────────────────────────────────────────────

# dx = 5 nm per sample, so a spacing of n samples is 5n nm.
_RAW_X = np.arange(0, 2.0, 0.005)


def test_periods_from_a_single_groove_fall_back_to_the_estimate():
    """One groove gives no spacing to measure, so the estimate must stand"""
    period, std, spacings = _quiet(_calculate_periods, _RAW_X, np.array([10]), 250.0)
    assert period == 250.0
    assert std == 0
    assert spacings == []


def test_periods_from_two_grooves_measure_the_one_spacing():
    period, std, spacings = _quiet(_calculate_periods, _RAW_X, np.array([10, 60]), 250.0)
    assert np.isclose(period, 250.0), period       # 50 samples x 5 nm
    assert std == 0.0, "a single spacing has no spread"
    assert spacings == [250.0]


def test_periods_from_several_grooves_match_the_hand_computed_spacings():
    centers = np.array([0, 10, 25, 33])
    period, std, spacings = _quiet(_calculate_periods, _RAW_X, centers, 250.0)

    expected = [50.0, 75.0, 40.0]                  # diffs of 10, 15, 8 samples
    assert spacings == expected, spacings
    assert np.isclose(period, np.mean(expected))
    # np.std, not np.std(ddof=1) - these are the spacings themselves, not a
    # sample drawn from a wider population.
    assert np.isclose(std, np.std(expected)), std


def test_local_period_of_a_lone_groove_is_the_global_estimate():
    assert _calculate_local_periods([5], [], 250.0) == [250.0]


def test_local_periods_at_the_ends_use_the_one_neighbour_available():
    spacings = [100.0, 200.0, 300.0]
    local = _calculate_local_periods([1, 2, 3, 4], spacings, 250.0)
    assert local[0] == spacings[0], "first groove has no left neighbour"
    assert local[-1] == spacings[-1], "last groove has no right neighbour"


def test_local_periods_in_the_middle_average_both_neighbours():
    spacings = [100.0, 200.0, 300.0]
    local = _calculate_local_periods([1, 2, 3, 4], spacings, 250.0)
    assert local == [100.0, 150.0, 250.0, 300.0], local


def test_the_row_group_local_period_helper_is_the_same_function():
    """
    _calculate_local_periods_for_grooves is currently a pure passthrough.

    Pinned rather than removed: the two analysis paths keep parallel copies of
    several helpers, and this records that these two have not diverged.
    """
    spacings = [100.0, 200.0, 300.0]
    assert (_calculate_local_periods_for_grooves([1, 2, 3, 4], spacings, 250.0) ==
            _calculate_local_periods([1, 2, 3, 4], spacings, 250.0))


# ── Variance decomposition ───────────────────────────────────────────────────

def _quality(*slopes, **extra):
    return [dict({'blaze_slope': s}, **extra) for s in slopes]


def test_variance_decomposition_matches_the_hand_computation():
    """
    The claim the reported uncertainties rest on: total variance is the
    groove-to-groove spread plus the mean squared fit uncertainty.
    """
    stats = _calculate_statistics([10.0, 20.0, 30.0],
                                  _quality(0.1, 0.2, 0.3),
                                  [], [1.0, 1.0, 1.0])

    assert np.isclose(stats['physical_variance'], 100.0)     # var([10,20,30], ddof=1)
    assert np.isclose(stats['measurement_variance'], 1.0)    # mean of 1^2
    assert np.isclose(stats['total_std'] ** 2, 101.0)
    assert np.isclose(stats['sem'], np.sqrt(101.0 / 3.0))
    assert np.isclose(stats['mean_slope'], 0.2)


def test_groove_spread_is_a_sample_variance_but_local_spread_is_not():
    """
    Two different formulas in one function, and easy to unify by accident.

    std_angle uses ddof=1: the grooves measured are a sample of the grating.
    local_angle_std uses ddof=0: the local angles along a facet are the whole
    of what was measured, not a sample of something larger.
    """
    local = [1.0, 2.0, 3.0, 10.0]
    stats = _calculate_statistics([10.0, 20.0, 30.0], _quality(0.1, 0.2, 0.3),
                                  local, [])

    assert np.isclose(stats['local_angle_std'], np.std(local))
    assert not np.isclose(stats['local_angle_std'], np.std(local, ddof=1)), \
        "local_angle_std switched to a sample variance"
    assert np.isclose(stats['std_angle'], np.std([10.0, 20.0, 30.0], ddof=1))
    assert np.isclose(stats['local_angle_range'], 9.0)


def test_without_fit_uncertainties_the_total_is_the_physical_spread_alone():
    stats = _calculate_statistics([10.0, 20.0, 30.0], _quality(0.1, 0.2, 0.3),
                                  [], [])
    assert stats['measurement_variance'] == 0
    assert stats['mean_measurement_uncertainty'] == 0
    assert np.isclose(stats['total_std'] ** 2, stats['physical_variance'])


def test_steep_angle_is_none_when_no_groove_reported_one():
    stats = _calculate_statistics([1.0, 2.0], _quality(0.1, 0.2), [], [])
    assert stats['mean_steep'] is None, \
        "absent steep angles must not average to 0 - that reads as a measurement"


def test_steep_angle_averages_only_the_grooves_that_have_one():
    quality = [{'blaze_slope': 0.1, 'steep_angle': 60.0},
               {'blaze_slope': 0.2},
               {'blaze_slope': 0.3, 'steep_angle': 62.0}]
    stats = _calculate_statistics([1.0, 2.0, 3.0], quality, [], [])
    assert np.isclose(stats['mean_steep'], 61.0)


def test_a_single_groove_gives_an_undefined_spread_not_zero():
    """
    Existing behaviour, recorded rather than proposed as a fix.

    One measurement cannot say how much grooves differ from each other, and
    np.var(ddof=1) says so with nan. Reporting 0 would claim a perfectly
    uniform grating on the strength of one groove.
    """
    with warnings.catch_warnings():
        warnings.simplefilter('ignore')
        stats = _calculate_statistics([25.0], _quality(0.5), [], [0.1])

    assert np.isnan(stats['physical_variance'])
    assert np.isnan(stats['sem'])


# ── Row groups and the correlation correction ────────────────────────────────

def test_labels_and_angles_of_different_lengths_raise():
    try:
        _calculate_statistics_row_groups([1.0, 2.0, 3.0], _quality(0, 0, 0),
                                         [], [0.0, 0.0, 0.0], [0, 0])
    except ValueError:
        return
    raise AssertionError("mismatched lengths should raise ValueError")


def test_within_image_spread_is_the_spread_of_the_group_means():
    angles = [10.0, 10.0, 20.0, 20.0, 30.0, 30.0]
    stats = _calculate_statistics_row_groups(
        angles, _quality(*[0.0] * 6), [], [0.0] * 6, [0, 0, 1, 1, 2, 2])

    assert stats['n_groups'] == 3
    assert np.isclose(stats['within_image_std'],
                      np.std([10.0, 20.0, 30.0], ddof=1))


def test_icc_matches_the_hand_computed_variance_ratio():
    """
    The same fixture as test_icc.py's hand-computed case, driven through the
    analyzer rather than through compute_icc, so the wiring is checked too.

    group means 1.5 and 11.5 -> between_var = 50; each group var = 0.5
    -> icc = 50 / 50.5
    """
    angles = [1.0, 2.0, 11.0, 12.0]
    labels = [0, 0, 1, 1]
    stats = _calculate_statistics_row_groups(
        angles, _quality(*[0.0] * 4), [], [0.0] * 4, labels)

    assert np.isclose(stats['icc'], 50.0 / 50.5), stats['icc']
    # n_eff = n / (1 + (m - 1) * icc), with n = 4 and m = 2
    assert np.isclose(stats['n_effective'], 4.0 / (1.0 + 1.0 * (50.0 / 50.5)))
    assert np.isclose(stats['design_effect'], 4.0 / stats['n_effective'])
    assert np.isclose(stats['sem_corrected'],
                      stats['total_std'] / np.sqrt(stats['n_effective']))


def test_zero_correlation_leaves_the_standard_error_untouched():
    """
    At ICC = 0 the effective sample size is the real one and the correction is
    the identity. Identical angles with a real fit uncertainty make the check
    non-trivial: the standard error is 0.5, not 0.
    """
    stats = _calculate_statistics_row_groups(
        [5.0, 5.0, 5.0, 5.0], _quality(*[0.0] * 4), [],
        [1.0, 1.0, 1.0, 1.0], [0, 0, 1, 1])

    assert stats['icc'] == 0.0
    assert stats['n_effective'] == 4.0
    assert stats['sem'] > 0, "measurement uncertainty alone should give a SEM"
    assert stats['sem_corrected'] == stats['sem']


def test_a_small_correlation_still_inflates_the_error_of_large_groups():
    """
    Why the correction is not optional at the ICC values this project measures.

    The design effect is 1 + (m - 1) * ICC, so it is driven by group size as
    much as by correlation. Twenty measurements per row group turn an ICC of
    0.04 - 'negligible' by the usual thresholds - into a standard error a third
    larger than the uncorrected one.
    """
    rng = np.random.default_rng(42)
    angles = rng.normal(30.0, 1.0, 400)
    labels = np.repeat(np.arange(20), 20)

    stats = _calculate_statistics_row_groups(
        angles, _quality(*[0.0] * 400), [], [0.0] * 400, labels)

    assert stats['icc'] < 0.1, stats['icc']
    assert np.isclose(stats['design_effect'], 1.0 + (20 - 1) * stats['icc'])
    assert stats['sem_corrected'] > stats['sem'], \
        "a small ICC over groups of 20 still costs a third of the precision"


def test_strongly_grouped_measurements_inflate_the_standard_error():
    """The whole point of the correction: correlated repeats are worth less"""
    rng = np.random.default_rng(0)
    angles, labels = [], []
    for group, offset in enumerate(rng.normal(0, 5.0, 20)):
        angles.extend(30.0 + offset + rng.normal(0, 0.1, 20))
        labels.extend([group] * 20)

    stats = _calculate_statistics_row_groups(
        angles, _quality(*[0.0] * len(angles)), [], [0.0] * len(angles), labels)

    assert stats['icc'] > 0.9, stats['icc']
    assert stats['sem_corrected'] > stats['sem']


def test_one_row_group_leaves_the_standard_error_uncorrected():
    """
    With a single group the ICC is undefined, and the guard must fall back to
    the plain SEM rather than propagate nan into the reported uncertainty.
    """
    angles = [1.0, 2.0, 3.0]
    stats = _calculate_statistics_row_groups(
        angles, _quality(0.0, 0.0, 0.0), [], [0.0] * 3, [0, 0, 0])

    assert np.isnan(stats['icc'])
    assert np.isnan(stats['design_effect'])
    assert stats['n_effective'] == float(len(angles))
    assert stats['sem_corrected'] == stats['sem']


def test_group_attribution_follows_the_labels_not_a_groove_count():
    """
    The regression this path was rebuilt around.

    Group membership used to be reconstructed by slicing the angle list by each
    group's *detected* groove count. Angles are only appended when a fit
    succeeds, so a single failure shifted every later group.

    The 4-and-2 split matters: any reconstruction that divides six angles
    positionally into two groups splits them 3 and 3, giving group means of
    12.0 and 26.0 instead of 13.0 and 31.0. A 3-and-2 split would not
    discriminate - both readings agree there - so this test would pass while
    measuring nothing.

    test_icc.py covers the same bug end-to-end on a real scan; this is the
    arithmetic on its own.
    """
    angles = [10.0, 12.0, 14.0, 16.0, 30.0, 32.0]
    labels = [0, 0, 0, 0, 1, 1]
    stats = _calculate_statistics_row_groups(
        angles, _quality(*[0.0] * 6), [], [0.0] * 6, labels)

    expected_means = [np.mean(angles[:4]), np.mean(angles[4:])]
    assert expected_means == [13.0, 31.0]
    assert stats['n_groups'] == 2
    assert np.isclose(stats['within_image_std'], np.std(expected_means, ddof=1))


# ── The result dictionaries ──────────────────────────────────────────────────

def test_traditional_results_carry_the_angles_and_trim_the_centres():
    angles = [10.0, 20.0, 30.0]
    quality = _quality(0.1, 0.2, 0.3)
    stats = _calculate_statistics(angles, quality, [], [1.0, 1.0, 1.0])

    result = _package_results('scan.txt', angles, stats, 250.0, 1.5,
                              [250.0, 250.0], quality, [],
                              np.arange(10.0), np.arange(10.0),
                              np.array([1, 2, 3, 4, 5]))

    assert result['n_grooves'] == 3
    assert result['min_angle'] == 10.0 and result['max_angle'] == 30.0
    assert np.isclose(result['sem'], stats['sem'])
    assert list(result['groove_centers']) == [1, 2, 3], \
        "centres should be trimmed to the grooves that produced a fit"


def test_traditional_results_omit_the_row_group_fields():
    """The two modes return different shapes, and downstream code branches on it"""
    angles = [10.0, 20.0, 30.0]
    quality = _quality(0.1, 0.2, 0.3)
    stats = _calculate_statistics(angles, quality, [], [1.0, 1.0, 1.0])

    result = _package_results('scan.txt', angles, stats, 250.0, 1.5, [], quality,
                              [], np.arange(10.0), np.arange(10.0),
                              np.array([1, 2, 3]))

    for key in ('n_groups', 'groove_row_groups', 'icc', 'sem_corrected'):
        assert key not in result, f"{key} belongs to the row-group path only"


def test_row_group_results_fall_back_when_the_statistics_lack_icc_fields():
    """
    _package_results_row_groups reads the correlation fields defensively. A
    stats dict without them must still produce a well-formed result.
    """
    angles = [10.0, 20.0, 30.0]
    quality = _quality(0.1, 0.2, 0.3)
    stats = _calculate_statistics(angles, quality, [], [1.0, 1.0, 1.0])

    result = _package_results_row_groups('scan.txt', angles, stats, 250.0, 1.5,
                                         [], quality, [], np.arange(10.0),
                                         [], [0, 0, 1])

    assert result['within_image_std'] == 0
    assert result['icc'] is None
    assert result['n_effective'] is None
    assert result['groove_row_groups'] == [0, 0, 1]


def test_row_group_results_without_any_group_have_nothing_to_plot():
    angles = [10.0, 20.0, 30.0]
    quality = _quality(0.1, 0.2, 0.3)
    stats = _calculate_statistics(angles, quality, [], [1.0, 1.0, 1.0])

    result = _package_results_row_groups('scan.txt', angles, stats, 250.0, 1.5,
                                         [], quality, [], np.arange(10.0),
                                         [], [0, 0, 1])

    assert result['flat_y'] is None
    assert result['groove_centers'] == []


# ── Failure paths ────────────────────────────────────────────────────────────

def test_a_missing_file_is_reported_not_raised():
    """
    _load_and_validate soft-fails so a batch run does not stop on one bad file.
    """
    assert _quiet(_load_and_validate, '/nonexistent/scan.txt', _settings()) == \
        (None, None)


def test_analysis_of_a_missing_file_returns_none_in_both_modes():
    for use_row_groups in (True, False):
        settings = _settings(use_row_groups=use_row_groups)
        assert _quiet(analyze_single_file, '/nonexistent/scan.txt',
                      show_plots=False, settings=settings) is None, use_row_groups


def test_a_featureless_scan_finds_no_grooves_in_both_modes():
    for use_row_groups in (True, False):
        settings = _settings(use_row_groups=use_row_groups)
        assert _quiet(analyze_single_file, _flat_path(),
                      show_plots=False, settings=settings) is None, use_row_groups


def test_a_trim_that_consumes_the_facet_yields_no_measurements():
    """
    Above MAX_FACET_TRIM the trim eats the whole facet and every fit fails.

    analyzer.py never calls settings.validate(), so an out-of-range trim reaches
    the fitting code unchecked - this records what happens when it does, which
    is a clean None rather than a crash or an empty-mean nan.
    """
    for use_row_groups in (True, False):
        settings = _settings(use_row_groups=use_row_groups, facet_trim=0.45)
        assert _quiet(analyze_single_file, _grating_path(),
                      show_plots=False, settings=settings) is None, use_row_groups


# ── End to end, against a known angle ────────────────────────────────────────

# The pipeline recovers the synthetic angle about 0.15 deg low, and does so
# whatever the sampling density - it is the linear detrend of a finite window
# biasing the facet slope, not a discretisation error. The tolerance below
# leaves room for that without admitting a real regression, which would show up
# as degrees rather than tenths.
ANGLE_TOL_DEG = 0.5


def test_the_traditional_path_recovers_the_known_blaze_angle():
    result = _quiet(_analyze_single_file_traditional, _grating_path(),
                    show_plots=False, settings=_settings(use_row_groups=False))

    assert result is not None
    assert result['n_grooves'] > 0
    assert abs(result['mean_angle'] - BLAZE_ANGLE_DEG) < ANGLE_TOL_DEG, \
        f"recovered {result['mean_angle']:.3f} deg from a {BLAZE_ANGLE_DEG} deg facet"
    assert np.isclose(result['period_nm'], PERIOD_NM, atol=1.0), result['period_nm']


def test_the_row_group_path_recovers_the_known_blaze_angle():
    result = _quiet(analyze_single_file_with_row_groups, _grating_path(),
                    show_plots=False, settings=_settings(use_row_groups=True))

    assert result is not None
    assert abs(result['mean_angle'] - BLAZE_ANGLE_DEG) < ANGLE_TOL_DEG, \
        f"recovered {result['mean_angle']:.3f} deg from a {BLAZE_ANGLE_DEG} deg facet"
    assert result['n_groups'] == N_ROW_GROUPS
    assert len(result['groove_row_groups']) == len(result['all_angles'])


def test_both_modes_agree_on_the_angle_of_the_same_grating():
    """
    Row grouping measures each groove once per band instead of once per image.
    It should multiply the measurement count without moving the answer.
    """
    traditional = _quiet(_analyze_single_file_traditional, _grating_path(),
                         show_plots=False,
                         settings=_settings(use_row_groups=False))
    row_groups = _quiet(analyze_single_file_with_row_groups, _grating_path(),
                        show_plots=False, settings=_settings(use_row_groups=True))

    assert np.isclose(traditional['mean_angle'], row_groups['mean_angle'],
                      atol=ANGLE_TOL_DEG)
    assert row_groups['n_grooves'] > traditional['n_grooves']


# ── Dispatch ─────────────────────────────────────────────────────────────────

def test_use_row_groups_selects_the_row_group_path():
    settings = _settings(use_row_groups=True)
    dispatched = _quiet(analyze_single_file, _grating_path(),
                        show_plots=False, settings=settings)
    direct = _quiet(analyze_single_file_with_row_groups, _grating_path(),
                    show_plots=False, settings=settings)

    for key in ('mean_angle', 'n_grooves', 'n_groups', 'period_nm', 'sem'):
        assert np.isclose(dispatched[key], direct[key]), key
    assert dispatched['all_angles'] == direct['all_angles']


def test_disabling_row_groups_selects_the_traditional_path():
    settings = _settings(use_row_groups=False)
    dispatched = _quiet(analyze_single_file, _grating_path(),
                        show_plots=False, settings=settings)
    direct = _quiet(_analyze_single_file_traditional, _grating_path(),
                    show_plots=False, settings=settings)

    for key in ('mean_angle', 'n_grooves', 'period_nm', 'sem'):
        assert np.isclose(dispatched[key], direct[key]), key
    assert 'n_groups' not in dispatched, \
        "the traditional path should not report row groups"


if __name__ == '__main__':
    failures = 0
    for name, fn in sorted(globals().items()):
        if not name.startswith('test_'):
            continue
        try:
            fn()
            print(f"PASS  {name}")
        except AssertionError as exc:
            failures += 1
            print(f"FAIL  {name}: {exc}")
    print(f"\n{'all tests passed' if not failures else f'{failures} failure(s)'}")
    sys.exit(1 if failures else 0)
